[build]
  command = "pnpm build"

[dev]
  command = "pnpm dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Access-Control-Allow-Origin = "*"
